---
title: "Experiments with groups of stations: using kmeans for 4 clusters with lake_perc and catchment_size as params"
author: "FBK"
date: "9 januar 2017"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='images/',
                      echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE)
```

```{r sourcing}

load("data/flood_metadata.RData")
load("data/flood_data.RData")
source("global.R")

lake_normalized <- flood_metadata$perc_lake / max(flood_metadata$perc_lake, na.rm = TRUE)
flood_metadata$area_total[24] <- NA # Getting rid of station n24 which has a much bigger catchment than the others
area_normalized <- flood_metadata$area_total / max(flood_metadata$area_total, na.rm = TRUE)

initial_index <- seq(along = flood_metadata$median_julian)
to_cluster <- na.omit(data.frame(lake = lake_normalized, area = area_normalized, index = initial_index))

set.seed(20)
stationsCluster <- kmeans(to_cluster[1:2], 4, nstart = 20)

st_selection_1 <- c()
st_selection_2 <- c()
st_selection_3 <- c()
st_selection_4 <- c()

for (i in seq(along = to_cluster$index)) {

if (stationsCluster$cluster[[i]] == 1) {st_selection_1[i] <- to_cluster$index[i]}
if (stationsCluster$cluster[[i]] == 2) {st_selection_2[i] <- to_cluster$index[i]}
if (stationsCluster$cluster[[i]] == 3) {st_selection_3[i] <- to_cluster$index[i]}
if (stationsCluster$cluster[[i]] == 4) {st_selection_4[i] <- to_cluster$index[i]}
  
}

st_selection_1 <- c(24,24)  # HACK as this station is alone in its cluster
st_selection_2 <- as.vector(na.omit(st_selection_2))
st_selection_3 <- as.vector(na.omit(st_selection_3))
st_selection_4 <- as.vector(na.omit(st_selection_4))

  
print("st_selection_1")
st_selection_1
print("st_selection_2")
st_selection_2
print("st_selection_3")
st_selection_3
print("st_selection_4")
st_selection_4

## TO plot the clusters in 2D
plot(to_cluster[1:2], xlab("lake"), ylab("size"),
          col = stationsCluster$cluster,
          pch = 20, cex = 3)

```

## QS

#### QS 2y

```{r QS_2y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "QS"
returnPeriod <- 2

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### QS 10y

```{r QS_10y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}

returnPeriod <- 10

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### QS 30y

```{r QS_30y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 30

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

## BS

#### BS 2y

```{r BS_2y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "BS"
returnPeriod <- 2

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### BS 10y

```{r BS_10y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 10

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### BS 30y

```{r BS_30y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 30

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

## Return levels

#### RL 10y

```{r RL_10y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "r.levels"
returnPeriod <- 10

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### RL 100y

```{r RL_100y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 100

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### RL 200y

```{r RL_200y_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 200

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

## KS

```{r KS_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "KS"

plot4server_gof_averaged(gof_type, 30,150, st_selection_1)
plot4server_gof_averaged(gof_type, 30,150, st_selection_2)
plot4server_gof_averaged(gof_type, 30,150, st_selection_3)
plot4server_gof_averaged(gof_type, 30,150, st_selection_4)
```

## AD

```{r AD_median_fgp_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "AD"

plot4server_gof_averaged(gof_type, 30,150, st_selection_1)
plot4server_gof_averaged(gof_type, 30,150, st_selection_2)
plot4server_gof_averaged(gof_type, 30,150, st_selection_3)
plot4server_gof_averaged(gof_type, 30,150, st_selection_4)

```

