---
title: "Experiments with groups of stations: julian date quantiles"
author: "FBK"
date: "9 januar 2017"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='images/',
                      echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE)
```

```{r sourcing}

load("data/flood_metadata.RData")
load("data/flood_data.RData")
source("global.R")

q50 <- median(na.omit(flood_metadata$median_julian))
q25 <- quantile(na.omit(flood_metadata$median_julian), 0.25)
q75 <- quantile(na.omit(flood_metadata$median_julian), 0.75)

print("q25")
print(q25)
print("q50")
print(q50)
print("q75")
print(q75)

st_selection_1 <- which(flood_metadata$median_julian < q25)
st_selection_2 <- which(flood_metadata$median_julian > q25 & flood_metadata$median_julian < q50)
st_selection_3 <- which(flood_metadata$median_julian > q50 & flood_metadata$median_julian < q75)
st_selection_4 <- which(flood_metadata$median_julian > q75)
```

## QS

```{r QS_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "QS"
returnPeriod <- 2

plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_4)
```


## BS

```{r BS_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "BS"
returnPeriod <- 2

plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_QSBS_ave(gof_type, returnPeriod,30,150, st_selection_4)
```


## Return levels

#### RL 10y

```{r RL_10y_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "r.levels"
returnPeriod <- 10

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### RL 100y

```{r RL_100y_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 100

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

#### RL 200y

```{r RL_200y_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
returnPeriod <- 200

plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_1)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_2)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_3)
plot4server_rlevels_coeffvar_ave(gof_type, returnPeriod,30,150, st_selection_4)
```

## KS

```{r KS_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "KS"

plot4server_gof_averaged(gof_type, 30,150, st_selection_1)
plot4server_gof_averaged(gof_type, 30,150, st_selection_2)
plot4server_gof_averaged(gof_type, 30,150, st_selection_3)
plot4server_gof_averaged(gof_type, 30,150, st_selection_4)
```

## AD

```{r AD_median_julian_q25q50q75,  results = "asis", fig.height= 10, fig.width= 15, fig.keep = "all", fig.align='center'}
gof_type <- "AD"

plot4server_gof_averaged(gof_type, 30,150, st_selection_1)
plot4server_gof_averaged(gof_type, 30,150, st_selection_2)
plot4server_gof_averaged(gof_type, 30,150, st_selection_3)
plot4server_gof_averaged(gof_type, 30,150, st_selection_4)

```

